/*
 * Online payment of a specific order — the lawful use of a payment gateway.
 *
 * THE BUG THIS FIXES
 *
 * SSLCommerz was already integrated and works (37 methods, including bKash and Nagad).
 * But it was wired only to the top-up routes, which do:
 *
 *     UPDATE wallets SET balance_paisa = balance_paisa + $1
 *
 * That is the closed-loop path — the one production now refuses to boot into, because
 * holding student balances is issuing a prepaid payment instrument (PSS Act 2024 s.15(1)).
 * The lawful zero-float order flow had NO gateway path at all. So in the mode this system
 * actually ships in, there was no way for a student to pay online. Every component passed
 * its own tests; nothing tested the composition.
 *
 * The fix is a re-wiring, not a rewrite: a successful payment now settles ONE ORDER through
 * the ledger, instead of crediting a balance the university may not hold.
 *
 * THE THREE-STAGE MONEY MODEL
 *
 * Money does not go straight from the student to PUC's bank account, and pretending it does
 * is how reconciliation systems end up lying. There are three distinct events:
 *
 *   1. order raised     DR receivable:orders      CR revenue:merchant     (goods left the counter)
 *   2. student pays      DR clearing:gateway      CR receivable:orders     (gateway holds the money)
 *                        DR expense:fee
 *   3. gateway settles   DR bank                  CR clearing:gateway      (money reaches PUC)
 *
 * Stage 2 is this table. The gap between 2 and 3 is real — SSLCommerz settles on a T+n
 * cycle — and `clearing` is what makes that float visible rather than invisible.
 */

CREATE TABLE IF NOT EXISTS order_payments (
  id            BIGSERIAL   PRIMARY KEY,
  charge_id     BIGINT      NOT NULL REFERENCES charges(id) ON DELETE RESTRICT,

  gateway       TEXT        NOT NULL CHECK (length(btrim(gateway)) > 0),

  /*
   * Our identifier, sent to the gateway and echoed back. It is the join key on the
   * confirmation path, so it is UNIQUE and generated by us — never derived from anything
   * the browser can influence.
   */
  tran_id       TEXT        NOT NULL UNIQUE CHECK (length(btrim(tran_id)) > 0),
  session_key   TEXT,

  -- What we ASKED for. Compared against what the gateway says was actually paid.
  amount_paisa  BIGINT      NOT NULL CHECK (amount_paisa > 0),

  /*
   * DUPLICATE is the one that is easy to miss. A student can abandon session A, pay with
   * session B, and then A completes late at the gateway anyway. Both payments are real
   * money. Without a status for it, settling A would violate the partial unique index
   * below and surface as a raw constraint error — which the IPN handler would read as a
   * transient fault and ask the gateway to retry, forever.
   */
  status        TEXT        NOT NULL DEFAULT 'INITIATED'
                            CHECK (status IN ('INITIATED','PAID','FAILED','CANCELLED',
                                              'MISMATCH','DUPLICATE')),

  -- Everything below is the gateway's word, recorded verbatim for audit.
  val_id               TEXT,
  method               TEXT,
  bank_tran_id         TEXT,
  gateway_amount_paisa BIGINT,
  fee_paisa            BIGINT NOT NULL DEFAULT 0 CHECK (fee_paisa >= 0),

  ledger_posting_id    BIGINT REFERENCES ledger_postings(id) ON DELETE RESTRICT,
  note                 TEXT,

  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  paid_at       TIMESTAMPTZ,

  /*
   * A PAID row without a validation id or a ledger posting would be an assertion that money
   * arrived with nothing to prove it. Refuse to store one.
   */
  CONSTRAINT paid_rows_are_provable CHECK (
    status <> 'PAID' OR (
      val_id            IS NOT NULL AND
      ledger_posting_id IS NOT NULL AND
      paid_at           IS NOT NULL
    )
  )
);

/*
 * An order may be PAID online at most once.
 *
 * Partial, not a blanket UNIQUE on charge_id: a student who abandons the gateway and tries
 * again produces a second row, and that history is worth keeping. Only SETTLEMENT is
 * exclusive. Same reasoning as settlement_lines — a blanket unique index there made the
 * ALREADY_IMPORTED exception row itself unstorable.
 */
CREATE UNIQUE INDEX IF NOT EXISTS idx_order_payments_one_paid
  ON order_payments (charge_id) WHERE status = 'PAID';

CREATE INDEX IF NOT EXISTS idx_order_payments_charge ON order_payments (charge_id);
CREATE INDEX IF NOT EXISTS idx_order_payments_status ON order_payments (status, created_at DESC);

/* ------------------------------------------------------------------ view repairs
 *
 * The reconciliation views decided "settled" by `settlement_line_id IS NOT NULL`, which is
 * the acquirer's next-day statement. An order paid online is settled by a DIFFERENT rail
 * and never gets a settlement line — so without this repair every online payment would sit
 * in "sold but never paid for" forever, and the exception list would fill with false alarms
 * until nobody read it. An alert nobody reads is worse than no alert.
 */

CREATE OR REPLACE VIEW reconciliation_unsettled_orders AS
SELECT c.id, c.order_ref, c.amount_paisa, c.memo, c.created_at, c.expires_at, c.status,
       m.id AS merchant_id, m.name AS merchant_name,
       ROUND(EXTRACT(EPOCH FROM (now() - c.created_at)) / 3600.0, 1) AS age_hours
FROM charges c
JOIN merchants m ON m.id = c.merchant_id
WHERE c.order_ref IS NOT NULL
  AND c.settlement_line_id IS NULL
  AND c.status <> 'cancelled'
  AND NOT EXISTS (
    SELECT 1 FROM order_payments op WHERE op.charge_id = c.id AND op.status = 'PAID'
  )
ORDER BY c.created_at ASC;

CREATE OR REPLACE VIEW reconciliation_summary AS
WITH paid_online AS (
  SELECT DISTINCT charge_id FROM order_payments WHERE status = 'PAID'
),
settled AS (
  SELECT c.id,
         c.merchant_id,
         c.amount_paisa,
         c.status,
         (c.settlement_line_id IS NOT NULL OR po.charge_id IS NOT NULL) AS is_settled
  FROM charges c
  LEFT JOIN paid_online po ON po.charge_id = c.id
  WHERE c.order_ref IS NOT NULL
)
SELECT
  m.id   AS merchant_id,
  m.name AS merchant_name,
  COUNT(s.id)                                                                  AS orders_total,
  COUNT(s.id) FILTER (WHERE s.is_settled)                                      AS orders_settled,
  COUNT(s.id) FILTER (WHERE NOT s.is_settled AND s.status <> 'cancelled')      AS orders_unsettled,
  COALESCE(SUM(s.amount_paisa), 0)::BIGINT                                     AS gross_paisa,
  COALESCE(SUM(s.amount_paisa) FILTER (WHERE s.is_settled), 0)::BIGINT         AS settled_paisa,
  COALESCE(SUM(s.amount_paisa) FILTER (WHERE NOT s.is_settled AND s.status <> 'cancelled'), 0)::BIGINT
                                                                               AS unsettled_paisa
FROM merchants m
LEFT JOIN settled s ON s.merchant_id = m.id
GROUP BY m.id, m.name;

/*
 * Money the gateway is holding — collected from students, not yet in PUC's bank account.
 *
 * This is the number an accounts officer needs when the bank statement is smaller than the
 * day's sales and they want to know whether that is a problem or just the settlement cycle.
 */
CREATE OR REPLACE VIEW gateway_clearing_outstanding AS
SELECT op.gateway,
       COUNT(*)                                        AS payment_count,
       COALESCE(SUM(op.gateway_amount_paisa), 0)::BIGINT AS gross_paisa,
       COALESCE(SUM(op.fee_paisa), 0)::BIGINT          AS fee_paisa,
       MIN(op.paid_at)                                 AS oldest_paid_at,
       ROUND(EXTRACT(EPOCH FROM (now() - MIN(op.paid_at))) / 3600.0, 1) AS oldest_age_hours
FROM order_payments op
WHERE op.status = 'PAID'
GROUP BY op.gateway;
